#!/bin/sh
case "$1" in
    test)
        cat ccthead.m4 > test.m4
        cat one.m4 >> test.m4
        m4 test.m4 | dpic -s > test.mp
        cp figbegin.mp tstfig.mp
        cat test.mp >> tstfig.mp
        cat figend.mp >> tstfig.mp
        mpost tstfig.mp
        for epsbympost in tstfig.*; do
            destfile=tstfig`expr $epsbympost : 'tstfig.\([0-9]\+\)'`.mps
            if (test $destfile != tstfig.mps); then
                mv $epsbympost $destfile
            fi
        done
        echo "\input figrlsbg.tex" > figrls.tex
        for name in tstfig*mps; do
            echo "\includegraphics{$name} \newpage" >> figrls.tex
        done
        echo "\input figrlsed.tex" >> figrls.tex
        pdflatex figrls
        pdfcrop figrls.pdf figures.pdf
        acroread figures.pdf
        ;;
    out)
        cat one.m4 >> work.m4
        ;;
    *)
        m4 -I /usr/local/lib/m4/circuit_macros cct.m4 | dpic -g > cct.tex
        xelatex form
        pdfcrop form.pdf figures.pdf
        ;;
esac
